//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EssenceUDK.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EssenceUDK.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dates and numbers are formatted according to the selected language:.
        /// </summary>
        internal static string Label_Bindings_Date {
            get {
                return ResourceManager.GetString("Label_Bindings_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Callback:.
        /// </summary>
        internal static string Label_CodeBehind_Callback {
            get {
                return ResourceManager.GetString("Label_CodeBehind_Callback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formatted value:.
        /// </summary>
        internal static string Label_CodeBehind_Format {
            get {
                return ResourceManager.GetString("Label_CodeBehind_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value from resources:.
        /// </summary>
        internal static string Label_CodeBehind_Resource {
            get {
                return ResourceManager.GetString("Label_CodeBehind_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Format string from resources:.
        /// </summary>
        internal static string Label_CodeBehind_ResourceFormat {
            get {
                return ResourceManager.GetString("Label_CodeBehind_ResourceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flag:.
        /// </summary>
        internal static string Label_Flag {
            get {
                return ResourceManager.GetString("Label_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language:.
        /// </summary>
        internal static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language (this panel only):.
        /// </summary>
        internal static string Label_Multilingual_Language {
            get {
                return ResourceManager.GetString("Label_Multilingual_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Non UI thread:.
        /// </summary>
        internal static string Label_Multithreading_NonUIThread {
            get {
                return ResourceManager.GetString("Label_Multithreading_NonUIThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected language:.
        /// </summary>
        internal static string Label_SelectedLanguage {
            get {
                return ResourceManager.GetString("Label_SelectedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default (English (US)).
        /// </summary>
        internal static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This is a template in style..
        /// </summary>
        internal static string Text_ComplexTemplate {
            get {
                return ResourceManager.GetString("Text_ComplexTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The current .NET culture is: {0}..
        /// </summary>
        internal static string Text_CurrentCulture {
            get {
                return ResourceManager.GetString("Text_CurrentCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The callback has been called {0} times..
        /// </summary>
        internal static string Text_LanguageChanges {
            get {
                return ResourceManager.GetString("Text_LanguageChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The current time is: {0}..
        /// </summary>
        internal static string Text_Multithreading_CurrentTime {
            get {
                return ResourceManager.GetString("Text_Multithreading_CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Non-dependency properties can be localized in XAML and code-behind..
        /// </summary>
        internal static string Text_NonDependencyProperty {
            get {
                return ResourceManager.GetString("Text_NonDependencyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This is an inline template..
        /// </summary>
        internal static string Text_SimpleTemplate {
            get {
                return ResourceManager.GetString("Text_SimpleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This text can have different color, font, size and margin..
        /// </summary>
        internal static string Text_StyleMessage {
            get {
                return ResourceManager.GetString("Text_StyleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bindings.
        /// </summary>
        internal static string Title_Bindings {
            get {
                return ResourceManager.GetString("Title_Bindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code-behind localization.
        /// </summary>
        internal static string Title_CodeBehind {
            get {
                return ResourceManager.GetString("Title_CodeBehind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiple languages.
        /// </summary>
        internal static string Title_Multilingual {
            get {
                return ResourceManager.GetString("Title_Multilingual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiple threads.
        /// </summary>
        internal static string Title_Multithreading {
            get {
                return ResourceManager.GetString("Title_Multithreading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiple Resource Files.
        /// </summary>
        internal static string Title_ResourceFiles {
            get {
                return ResourceManager.GetString("Title_ResourceFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Styles.
        /// </summary>
        internal static string Title_Style {
            get {
                return ResourceManager.GetString("Title_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Non-dependency properties and templates.
        /// </summary>
        internal static string Title_Templates {
            get {
                return ResourceManager.GetString("Title_Templates", resourceCulture);
            }
        }
    }
}
